### ISSUE TITLE
Docker builds a huge image when user id is too high

### ISSUE THREAD

**Issue by xposix** [Cisco-Talos/clamav-docker#46]
In the company I'm working at the moment, we are using Openshift, for some reason, it restricts the user ids in the `securityContext` `runAsUser` section of the Deployment. In our case, the minimum user id allowed is `1009510001` . This means we have to create the Docker image from scratch, following the instructions in this site.

To my surprise, the final Docker image was 327GBin size:
```
clavam-test         latest         b3e08a0c3f2b   2 days ago      327GB
```
which was OK for my laptop but caused my Jenkins to fail on every build.

After A LOT of troubleshooting, we find out that `useradd` command was causing several hundred of GB `/var/log/lastlog` file.

All this issues are solved if we added `--no-log-init` to useradd command in the Dockerfile like this:
```
    useradd --no-log-init -m -g clamav -s /bin/false --home-dir /var/lib/clamav -u 1009510000 -c "Clam Antivirus" clamav && \
```

After this we only had to add the following to the deployment.yaml of the official helm chart:

```
          securityContext:
            runAsUser: 1009510001
            runAsGroup: 1009510001
            allowPrivilegeEscalation: false
```
