### ISSUE TITLE
Container becomes unhealthy for recent image after 1.4.1-17

### ISSUE THREAD

**Issue by ackava** [Cisco-Talos/clamav-docker#71]
I am using container as mentioned below, 

```yml
version: '3.4'
name: cloud-server
services:
  clam-av:
    image: clamav/clamav
    restart: always
    container_name: clam-av
    volumes:
      - clamdb:/var/lib/clamav
      - /home/clam-av/:/tmp/
    ports:
      - 3310:3310
    environment:
      - FRESHCLAM_CHECKS=12
    networks:
      - sm_network
```

This docker compose has been functioning correctly since last 6 months, but after recent build, I started getting `ECONNREFUSED` for unix socket connection, so I tracked back working container image that was tagged with `:1.4.1-17`.

`clamav/clamav:1.4.1-17` works correctly, however recent image `clamav/clamav` published few hours ago and 7 days ago, starts correctly but after few seconds/minutes, container becomes unhealthy and I start getting `ECONNREFUSED`,

Unix socket exists on the file, and all permissions are correct, I checked if there was any recent changes to clam av configuration, but I didn't find any notable changes that would impact this.

Server has 8GB of RAM and more than 4GB is always free for clamav.

Container log doesn't log anything.

Running docker inspect also doesn't log anything except that docker ping couldn't connect to server hinting that the container is crashed.

I am traveling for few days now, however, if there is anyway to log detailed error, I will be happy to provide. Please let me know how can I help.
